### ISSUE TITLE
data.toJSON is not a function

### ISSUE THREAD

**Issue by jrock2004** [joelalejandro/feathers-hooks-jsonapify#21]
I tried adding this plugin and getting an error

```
info: Feathers application started on http://localhost:3030
info: after: contacts - Method: find
info: error: contacts - Method: find: data.toJSON is not a function
error:  TypeError: data.toJSON is not a function
    at /home/jcostanzo/Development/react-contact-manager/backend/node_modules/feathers-hooks-jsonapify/index.js:298:29
```
Here is my app.hooke.js file

```
// Application hooks that run for every service
const logger = require('./hooks/logger');
const jsonapify = require('feathers-hooks-jsonapify');

module.exports = {
  before: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  after: {
    all: [ logger(), jsonapify() ],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [ logger() ],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```

Am I doing something wrong?

Here is my data as rest

```
{
  "total": 2,
  "limit": 50,
  "skip": 0,
  "data": [
    {
      "_id": "5a5e1a9e4626e26585a191b7",
      "phone": "+18138683770",
      "email": "tony@starkenterprises.com",
      "updatedAt": "2018-01-16T15:30:38.060Z",
      "createdAt": "2018-01-16T15:30:38.060Z",
      "name": {
        "first": "Tony",
        "last": "Stark"
      },
      "__v": 0
    },
    {
      "_id": "5a5e3b6174510621fd44baac",
      "__v": 0,
      "email": "peter@spiderman.com",
      "phone": "+151233487",
      "updatedAt": "2018-01-16T17:50:25.590Z",
      "createdAt": "2018-01-16T17:50:25.590Z",
      "name": {
        "first": "Peter",
        "last": "Parker"
      }
    }
  ]
}
```

**Comment by ParraAlejandro** [comment]
I have the same error. I use knex with oracledb to connect to the base.
Apparently this is written only for mongo connectors.

**Comment by joelalejandro** [comment]
@jrock2004 @ParraAlejandro Sorry I haven't seen this before. I've used it for a MySQL connector without issues. I think the problem is that you're using it in the `all()` hook. Try something like this:

```
  after: {
    all: [],
    find: [ jsonapify() ],
    get: [ jsonapify() ],
    create: [ jsonapify() ],
    update: [ jsonapify() ],
    patch: [ jsonapify() ],
    remove: []
  },
```

**Comment by joelalejandro** [comment]
Also, this seems related to #18.

**Comment by ParraAlejandro** [comment]
@joelalejandro, I'm using the knex connector for the Oracle database. I also use feathers-knex and validation transactions with feathers-hooks-validate-joi. I have the error: 

`error:  TypeError: hook.result.toJSON is not a function  at Object.jsonapifyViaGet`

My code is : 

```
const schema = require("./mapeo-practicas-determinaciones.schema");
const validate = require('feathers-hooks-validate-joi');
const joiOptions = { convert: true, abortEarly: false };
const { hooks } = require('feathers-knex');
const { transaction } = hooks;
const jsonapify = require('feathers-hooks-jsonapify');

module.exports = {
  before: {
    all: [transaction.start()],
    find: [],
    get: [],
    create: [validate.form(schema, joiOptions)],
    update: [validate.form(schema, joiOptions)],
    patch:  [validate.form(schema, joiOptions)],
    remove: []
  },

  after: {
    all: [ transaction.end()],
    find: [],
    get:  [ jsonapify() ],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [ transaction.rollback()],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```

Modify the code to see the object "result" but the returned object is identical to my schema. It does not have the methods that jsonapify calls

```
..
 after: {
    all: [ transaction.end()],
    find: [],
    get:  [ (hook) => {console.log(hook)} ],
    create: [],
...
```
 In the console I see this: 

```
....
method: 'get',
  path: 'mapeo-practicas-determinaciones',
  result:
   { ID: 'XE-00000000002',
     ID_DETERMINACION_PRACTICA: 'XE-00000000021',
     CODE: 'P.47546',
     ID_MAPEO_PRACTICA: 'MSTR-000000111',
     SYSTEM: 'http://www.cdrossi.com/tests' } }
....
```

At this point I think that the objects returned by the connectors are different for each provider.

**Comment by joelalejandro** [comment]
@ParraAlejandro It's possible that the object transformations that occur on `hook.result` do not provide an implementation of `.toJSON()`. I'm thinking I could try to change it to a `JSON#stringify()` + `JSON#parse()` implementation. I'll give it a try - in the meantime, if you want, you could replace this line:

https://github.com/joelalejandro/feathers-hooks-jsonapify/blob/6c3282a2998992d250dbd560fa6a83edd50d154a/index.js#L340

with something like:

```js
const jsonItem = JSON.parse(JSON.stringify(hook.result);
```

**Comment by ParraAlejandro** [comment]
@joelalejandro  Change the code but throw this error: 

```
error:  TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at jsonapify (/home/alejandro/workspaces/sinergisResponsive/sinergisApiRest/node_modules/feathers-hooks-jsonapify/index.js:172:30)
    at Object.jsonapifyViaGet [as get] (/home/alejandro/workspaces/sinergisResponsive/sinergisApiRest/node_modules/feathers-hooks-jsonapify/index.js:342:18)
    at Object.<anonymous> (/home/alejandro/workspaces/sinergisResponsive/sinergisApiRest/node_modules/feathers-hooks-jsonapify/index.js:380:31)
    at promise.then.hookObject (/home/alejandro/workspaces/sinergisResponsive/sinergisApiRest/node_modules/@feathersjs/commons/lib/hooks.js:167:73)
    at <anonymous>
```

https://github.com/joelalejandro/feathers-hooks-jsonapify/blob/6c3282a2998992d250dbd560fa6a83edd50d154a/index.js#L172

In my program model.attributes is undefined.

**Comment by joelalejandro** [comment]
@ParraAlejandro That's weird. What happens if you simply use `hook.result`? I'm thinking that we could check for the method to exist:

```js
// Attempt to serialize as JSON, otherwise use raw object.
const jsonItem = hook.result.toJSON ? hook.result.toJSON() : hook.result;
```

**Comment by toovy** [comment]
Hi @joelalejandro,

I'm getting the same error. Created a fresh feathers-Project@3.2.3, generate the service bucket with the mongoose adapter, used Postman to create a bucket, GET localhost:3030/buckets works fine.

Next step, added the hook in app.hooks.js in after.get and after.find:

```
{
    "name": "GeneralError",
    "message": "after hook for 'find' method returned invalid hook object",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}
}
```

It does not matter if I use global hooks or the services hooks in buckets.hooks.js. Hope this helps with the analysis.

**Update:**

I've added the hook as local lib and was able to debug a bit. It seems that the mongoose adapter returns the data in a different way. The following line fails as the returned object has not toJSON method:

https://github.com/joelalejandro/feathers-hooks-jsonapify/blob/6c3282a2998992d250dbd560fa6a83edd50d154a/index.js#L298

I removed the call, but the next issue occurs here:

https://github.com/joelalejandro/feathers-hooks-jsonapify/blob/6c3282a2998992d250dbd560fa6a83edd50d154a/index.js#L172

The mongoose model has no property attributes, this seems to be dedicated to the sequelize adapter.

@joelalejandro I guess the hook has not been tested against mongoose. Would you mind updating the readme with a compatibility-matrix or at least the information which adapter has been tested? Only in a side sentence in the relationships section it is mentioned, that this feature works only with sequelize, so the reader would - as in my case - automatically assume that this hook works with all adapters. Thanks!

**Comment by joelalejandro** [comment]
:+1: Sounds great, @toovy. Sorry for the long time without responding, I've just been recently resuming maintenance on my open source projects.

**Comment by toovy** [comment]
I barely did anything ;) thanks for your commitment! 👍
